version: '3'

services:
  source_postgres:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      - POSTGRES_DB: source_db
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
    volumes:
      -./source_db_init/init.sql:/docker-entryponit-initdb.d/init.sql

  destination_postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      - POSTGRES_DB: destination_db
      - POSTGRES_USER: postgres
      - POSTGRES_PASSWORD: postgres
    
  elt_script:
    build:
      context: ./script_elt
      dockerfile: Dockerfile
    command: ["python", "script_elt.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres

networks:
  elt_network:
    driver: bridge