version: '3'

services:
  source_postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: source_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./source_db_init/init.sql:/docker-entryponit-initdb.d/init.sql

  destination_postgres:
    image: postgres:15
    ports:
      - "5434:5432"
    networks:
      - elt_network
    environment:
      POSTGRES_DB: destination_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    
  elt_script:
    build:
      context: ./
      dockerfile: Dockerfile
    command: ["python", "script_elt.py"]
    networks:
      - elt_network
    depends_on:
      - source_postgres
      - destination_postgres

  
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.4.7
    command: 
      [
        "run",
        "--profiles-dir",
        "/root",
        "--project-dir",
        "dbt"
      
      ]
    networks:
      - elt_network
    volumes:
      - ./postgres_dbt:/dbt
      - ~/.dbt:/root
    depends_on:
      - elt_script
    environment:
      DBT_PROFILE: default
      DBT_TARGET: dev


networks:
  elt_network:
    driver: bridge